language: python
install:
- pip install -r requirements.txt
- npm install -g webpack
- npm install
script: 
- webpack
- find . -type f \( -iname "*.py"   ! -iname "__init__.py" ! -path "./.venv/*" \) | xargs pylint