language: python
install:
        pip install -r requirements.txt
        npm install
script:
        find . -iname "*.py" | xargs pylint
        find . -iname "*.js" | xargs ./node_modules/eslint/bin/eslint.js
